/// <reference path='../../Foomo.Backbone/typescript/components/bundle.d.ts' />
///<reference path='../../Foomo.Jasmine/typescript/jasmine.d.ts' />
///<reference path='simple.ts' />
///<reference path='simpleHTML.ts' />
///<reference path='myComps.ts' />
///<reference path='list.ts' />
///<reference path='feedback.ts' />
///<reference path='select.ts' />
///<reference path='specs.ts' />
